In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\PP\DA\Python Practice\Medical_Appointment_Task 1.csv")

In [3]:
print(df1.sample(10))

           PatientId  AppointmentID Gender          ScheduledDay  \
6347    7.145712e+13        5660434      M  2016-05-04T16:31:10Z
106845  1.381248e+13        5768384      F  2016-06-03T07:33:07Z
21894   2.649822e+12        5682746      F  2016-05-10T18:26:48Z
96156   8.188544e+13        5709783      F  2016-05-17T14:31:38Z
16475   8.651174e+12        5622893      M  2016-04-26T13:13:46Z
65620   1.371630e+13        5652322      F  2016-05-03T09:56:35Z
75584   1.195653e+12        5729952      F  2016-05-24T07:59:11Z
76486   6.167336e+12        5677826      F  2016-05-10T07:42:14Z
81198   3.474190e+13        5691156      F  2016-05-12T11:30:23Z
73566   8.512183e+13        5655250      F  2016-05-03T16:25:53Z

              AppointmentDay  Age    Neighbourhood  Scholarship  Hipertension  \
6347    2016-05-06T00:00:00Z   50       INHANGUETÁ            0             0
106845  2016-06-07T00:00:00Z   16    SANTOS DUMONT            0             0
21894   2016-05-20T00:00:00Z   68       GOIABEIRAS            0             1
96156   2016-06-01T00:00:00Z   19  JARDIM DA PENHA            0             0
16475   2016-05-20T00:00:00Z   18       TABUAZEIRO            0             0
65620   2016-05-10T00:00:00Z   27    SÃO CRISTÓVÃO            0             0
75584   2016-05-24T00:00:00Z   65   NOVA PALESTINA            0             1
76486   2016-05-10T00:00:00Z    1        CARATOÍRA            0             0
81198   2016-05-30T00:00:00Z   22           BONFIM            0             0
73566   2016-05-03T00:00:00Z   46      MARIA ORTIZ            0             0

        Diabetes  Alcoholism  Handcap  SMS_received No-show
6347           0           0        0             0      No
106845         0           0        0             1      No
21894          1           0        0             0      No
96156          0           0        0             1      No
16475          0           0        0             0      No
65620          0           0        0             1      No
75584          1           0        0             0      No
76486          0           0        0             0      No
81198          0           0        0             1      No
73566          0           0        0             0      No

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [5]:
df1.describe()

,PatientId,AppointmentID,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [6]:
df1[df1.duplicated()].count()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [7]:
df1.isnull().count()

PatientId         110527
AppointmentID     110527
Gender            110527
ScheduledDay      110527
AppointmentDay    110527
Age               110527
Neighbourhood     110527
Scholarship       110527
Hipertension      110527
Diabetes          110527
Alcoholism        110527
Handcap           110527
SMS_received      110527
No-show           110527
dtype: int64

In [8]:
df1.rename(columns={
    'PatientId': 'Patient_id',
    'AppointmentID': 'Appointment_id',
    'ScheduledDay': 'Scheduled_day',
    'AppointmentDay': 'Appointment_day',
    'Neighbourhood': 'Neighbourhood',
    'Hipertension': 'Hypertension',
    'Handcap': 'Handicap',
    'SMS_received': 'SMS_received',
    'No-show': 'No_show'
}, inplace=True)

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Patient_id       110527 non-null  float64
 1   Appointment_id   110527 non-null  int64
 2   Gender           110527 non-null  object
 3   Scheduled_day    110527 non-null  object
 4   Appointment_day  110527 non-null  object
 5   Age              110527 non-null  int64
 6   Neighbourhood    110527 non-null  object
 7   Scholarship      110527 non-null  int64
 8   Hypertension     110527 non-null  int64
 9   Diabetes         110527 non-null  int64
 10  Alcoholism       110527 non-null  int64
 11  Handicap         110527 non-null  int64
 12  SMS_received     110527 non-null  int64
 13  No_show          110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [10]:
df1['Patient_id'] = df1['Patient_id'].astype('int64')
df1['Scheduled_day'] = pd.to_datetime(df1['Scheduled_day']).dt.date.astype('datetime64[ns]')
df1['Appointment_day'] = pd.to_datetime(df1['Appointment_day']).dt.date.astype('datetime64[ns]')
df1['Scheduled_day'] = df1['Scheduled_day'].dt.strftime('%d-%m-%Y')
df1['Appointment_day'] = df1['Appointment_day'].dt.strftime('%d-%m-%Y')

In [11]:
df1.sample(10)

,Patient_id,Appointment_id,Gender,Scheduled_day,Appointment_day,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Handicap,SMS_received,No_show
295,28117525366396,5470709,M,15-03-2016,29-04-2016,54,ANDORINHAS,0,1,1,0,0,0,No
35792,792139565742613,5660621,F,04-05-2016,11-05-2016,59,MARUÍPE,0,0,0,0,0,0,No
95554,423332436965,5748651,F,31-05-2016,02-06-2016,73,BONFIM,0,1,0,0,0,0,No
39301,877658942421789,5694758,M,13-05-2016,13-05-2016,69,JOANA D´ARC,0,0,0,0,0,0,No
25410,871374938638855,5631027,M,27-04-2016,04-05-2016,63,ROMÃO,0,0,0,1,0,0,No
21965,12621681241465,5649311,F,02-05-2016,12-05-2016,56,MARIA ORTIZ,0,0,0,0,0,1,Yes
41821,997278643945899,5741455,F,30-05-2016,30-05-2016,61,PONTAL DE CAMBURI,0,0,0,0,0,0,No
53250,7896293967868,5692824,F,12-05-2016,12-05-2016,19,SANTO ANTÔNIO,0,0,0,0,1,0,No
68953,81657624142781,5711852,M,18-05-2016,20-05-2016,78,CARATOÍRA,0,1,0,0,0,0,Yes
65217,218531453419123,5730642,M,24-05-2016,24-05-2016,0,JARDIM CAMBURI,0,0,0,0,0,0,No

In [12]:
df1.Age.value_counts()

Age
 0      3539
 1      2273
 52     1746
 49     1652
 53     1651
        ...
 115       5
 100       4
 102       2
 99        1
-1         1
Name: count, Length: 104, dtype: int64

In [13]:
print("Before change")
print("Patients with Age less than -1 -> {}".format(df1[df1.Age == -1].shape[0]))
print("Patients with Age equal to 0 -> {}".format(df1[df1.Age == 0].shape[0]))
print("Patients with Age greater than 110 -> {}".format(df1[df1.Age > 110].shape[0]))

# Keep only valid ages
df1 = df1[(df1["Age"] >= 0) & (df1["Age"] <= 110)]

print(df1["Age"].value_counts())

print("After change")
print("Patients with Age less than -1 -> {}".format(df1[df1.Age == -1].shape[0]))
print("Patients with Age equal to 0 -> {}".format(df1[df1.Age == 0].shape[0]))
print("Patients with Age greater than 110 -> {}".format(df1[df1.Age > 110].shape[0]))

Before change
Patients with Age less than -1 -> 1
Patients with Age equal to 0 -> 3539
Patients with Age greater than 110 -> 5
Age
0      3539
1      2273
52     1746
49     1652
53     1651
       ...
97       11
98        6
100       4
102       2
99        1
Name: count, Length: 102, dtype: int64
After change
Patients with Age less than -1 -> 0
Patients with Age equal to 0 -> 3539
Patients with Age greater than 110 -> 0

In [15]:
df1["No_show"] = df1["No_show"].replace({"Yes": 1, "No": 0})

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110521 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Patient_id       110521 non-null  int64
 1   Appointment_id   110521 non-null  int64
 2   Gender           110521 non-null  object
 3   Scheduled_day    110521 non-null  object
 4   Appointment_day  110521 non-null  object
 5   Age              110521 non-null  int64
 6   Neighbourhood    110521 non-null  object
 7   Scholarship      110521 non-null  int64
 8   Hypertension     110521 non-null  int64
 9   Diabetes         110521 non-null  int64
 10  Alcoholism       110521 non-null  int64
 11  Handicap         110521 non-null  int64
 12  SMS_received     110521 non-null  int64
 13  No_show          110521 non-null  int64
dtypes: int64(10), object(4)
memory usage: 12.6+ MB

In [18]:
df1.to_csv("Medical_cleaned.csv", index=False)